import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react'

import Slogan from '../components/slogan'
import WestPoint from '../components/westPoint'
import WestPointLogo from '../components/westPoint_logo'
import Mindful from '../components/mindful'
import Rocket from '../components/rokect_3d'
import Introvert from '../components/introvert'
import Can from '../components/can'
import Coaster from '../components/coaster'
import Smeg from '../components/website'
import Text from '../components/text'
import Button from '../components/button'
import SheReady from '../components/sheReady'
import Hand_3d from '../components/hand_3d'
import Fantasia from '../components/fantasia'
import SheReadyLogo from '../components/sheReady_logo'
import Verzel from '../components/verzel'
import Phone_3d from '../components/phone_3d'
import Poster_1 from '../components/poster1'
import Poster_2 from '../components/poster2'



export default function Home() {


  return (
    <>
      <Head>
        <title>Hazel Wang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.col1}>
          <div className={styles.container}>
            <WestPoint />
            <WestPointLogo />
            <Mindful />
            <Rocket />
            <Introvert />
            <Can />
            <Coaster />
            <Smeg />
          </div>
          <div className={styles.container}>
            <Slogan/>
          </div>
          <div className={styles.container}>
            <SheReady />
            <SheReadyLogo />
            <Hand_3d />
            <Fantasia />
            <Verzel />
            <Phone_3d />
            <Poster_1 />
            <Poster_2 />


          </div>
        </div>
        <Text />
        <Button />
      </main>
    </>
  )
}
